djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('myprojects/', include('myprojects.urls')),
    path('marstracker/', include('marstracker.urls'),name = 'marstracker'),
    path('admin/', admin.site.urls),
    
]

djangoproject/marstracker/urls.py
from django.urls import path
from marstracker.views import PlayerCreateView,PlayerUpdateView,PlayerDeleteView,PlayerList
from marstracker.views import GameList,GameCreateView,GameDeleteView,GameUpdateView,GameDetailView
from marstracker.views import GameResultCreateView,GameResultsDeleteView,form_error,add_all_players_view,index_view
from marstracker.views import MyLoginView,MyLogoutView

from . import views
app_name = "marstracker"    
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('',index_view , name='index'),
    path('login/',MyLoginView.as_view(),name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path("register", views.register_request, name="register"),

    path('game/',GameList.as_view(),name='game-list'),
    path('game/add/',GameCreateView.as_view(),name='game-add'),
    path('game/addall/<int:pk>/<int:numberofplayers>',add_all_players_view,name='game-add-all'),
    path('game/<int:pk>',GameDetailView.as_view(),name='game-detail'),
    path('game/<int:pk>/delete/',GameDeleteView.as_view(),name='game-delete'),

    path('gameresult/add',GameResultCreateView.as_view(),name='game-result-add'),
    path('gameresult/<int:pk>/delete',GameResultsDeleteView.as_view(),name='game-result-delete'),
    path('gameresult/<int:game>/<int:player>/update',GameUpdateView.as_view(),name='game-result-update'),

    path('player/',PlayerList.as_view(),name='player-list'),
    path('player/add/',PlayerCreateView.as_view(),name='player-add'),
    path('player/<int:pk>/',PlayerUpdateView.as_view(),name='player-update'),
    path('player/<int:pk>/delete/',PlayerDeleteView.as_view(),name='player-delete'),

    path('formerror',form_error,name='form-error'),

    


]

djangoproject/myprojects/urls.py
from django.urls import path
from django.contrib import admin

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

djangoproject/marstracker/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse


        
class Player(models.Model):

    
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    reg_date = models.DateField('Registration day',default=datetime.now)

    def __str__(self):
        return self.first_name +' '+ self.last_name

    def get_absolute_url(self):
        return reverse('marstracker:index')
    
class Game(models.Model):
    map_choices = [('S','Standard'),('H','Hellas'),('E','Elysium')]
    map_type = models.CharField(max_length = 50,choices=map_choices,default = 'S')
    pub_date = models.DateField('date played',default=datetime.now)
    players = models.ManyToManyField(Player,through='GameResults',related_name="games")

    
    def __str__(self):
        return str(self.map_type)+ "  " + str(self.pub_date) 
    
class GameResults(models.Model):
    final_score = models.IntegerField(default = 0)
    milestones_score = models.IntegerField(default = 0)
    awards_score = models.IntegerField(default = 0)
    tr_score = models.IntegerField(default = 0)
    card_score = models.IntegerField(default = 0)
    board_score = models.IntegerField(default = 0)
    player = models.ForeignKey(Player,on_delete=models.CASCADE,null=True)
    game = models.ForeignKey(Game,on_delete=models.CASCADE,null=True)
    class Meta:
        unique_together = ('player', 'game')
    def __str__(self):
        return str(self.game) + ' ' + str(self.player)

djangoproject/marstracker/forms.py
from django import forms
from .models import Player,Game
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class GameForm(forms.Form):
    final_score = forms.IntegerField()
    milestones_score = forms.IntegerField()
    awards_score = forms.IntegerField()
    tr_score = forms.IntegerField()
    card_score = forms.IntegerField()
    board_score = forms.IntegerField()

class PlayerForm(GameForm):
    player = forms.ModelMultipleChoiceField(Player.objects.all())

class GamesForm(forms.ModelForm):
    number_of_players = forms.IntegerField(min_value = 1, max_value =8)
    class Meta:
        model = Game
        fields = ['map_type']





# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

djangoproject/marstracker/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.template import loader
from django.http import HttpResponseRedirect,HttpResponse,Http404,HttpResponseNotFound
from django.urls import reverse,reverse_lazy
from django.views import generic
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic.edit import CreateView, DeleteView, UpdateView,FormView
from .models import Game,Player,GameResults
from .forms import GameForm,PlayerForm,GamesForm,NewUserForm
from django.forms import formset_factory
from django.contrib.auth import login
from django.contrib import messages

# class IndexView(generic.ListView):
#     template_name = 'marstracker/index.html'
#     context_object_name = 'latest_game_list'
#     def get_queryset(self):
#         user = self.request.user
#         queryset = super().get_queryset()
#         if user.is_authenticated:
#             queryset = queryset.filter(user=user)
#         else:           
#             queryset = queryset.none()
#         return queryset
    
def index_view(request):

    if request.user.is_authenticated:
        user = request.user
        context = {'username': user.username}
    else:
        context = {'nouser': 'User is not authenticated'}
    return render(request, 'marstracker/index.html', context)

class PlayerCreateView(CreateView):
    model = Player
    template_name = 'marstracker/player_add.html'
    fields = ['first_name','last_name']
    success_url = reverse_lazy('marstracker:player-list')

class PlayerUpdateView(UpdateView):
    model = Player
    fields = ['first_name','last_name']
    template_name = 'marstracker/player_add.html'

class PlayerDeleteView(DeleteView):
    model = Player
    success_url = reverse_lazy('marstracker:player-list')
    template_name = 'marstracker/player_confirm_delete.html'

class PlayerList(generic.ListView):
    template_name = 'marstracker/player_list.html'
    context_object_name = 'player_list'
    
    def get_queryset(self):
        "Return the last fifty registered plaers"
        return Player.objects.order_by('-reg_date')[:50]

class GameList(generic.ListView):
    template_name = 'marstracker/game_list.html'
    context_object_name = 'game_list'
    
    def get_queryset(self):
        "Return all games"
        return Game.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        players = Player.objects.all()
        game_results = GameResults.objects.all()
        context['game_results'] = game_results
        context['players'] = players
        return context
    
class GameCreateView(CreateView):
    model = Game
    form_class = GamesForm
    template_name = 'marstracker/game_add.html'

    number_of_players = 0

    def form_valid(self,form):
        self.number_of_players = form.cleaned_data['number_of_players']
        return super().form_valid(form)
    def get_success_url(self) -> str:
        success_url = reverse_lazy('marstracker:game-add-all',kwargs={'numberofplayers': self.number_of_players,'pk': Game.objects.latest('id').id})
        return success_url

def add_all_players_view(request,pk,numberofplayers):
    print(numberofplayers,pk)
    MyFormSet = formset_factory(PlayerForm,extra = numberofplayers)
    success_url = reverse_lazy('marstracker:game-list')
    error_url = reverse_lazy('marstracker:form-error')
    if request.method == "POST":
        formset = MyFormSet(request.POST)
        if formset.is_valid():
            form_error = False
            for subform in formset:
                print(subform.cleaned_data)
                game = Game.objects.get(pk = pk)
                player = subform.cleaned_data['player'][0]
                if not GameResults.objects.filter(player = player,game=game).exists():
                    game_results = GameResults(player = player,game = game)
                    game_results.final_score = subform.cleaned_data['final_score']
                    game_results.milestones_score = subform.cleaned_data['milestones_score']
                    game_results.awards_score = subform.cleaned_data['awards_score']
                    game_results.tr_score = subform.cleaned_data['tr_score']
                    game_results.card_score = subform.cleaned_data['card_score']
                    game_results.board_score = subform.cleaned_data['board_score']
                    game_results.save()
                else: 
                    form_error = True
            if form_error:
                return redirect(error_url)                       
            else:
                return redirect(success_url)
    else:
            formset = MyFormSet()

    return render(request, 'marstracker/game_add_all.html', {'formset':MyFormSet})

def form_error(request):
    return render(request,'marstracker/form_error')

class GameDetailView(generic.DetailView):
    model = Game
    template_name = 'marstracker/game_detail.html'
    context_object_name = 'game'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        players = Player.objects.all()
        game_id = self.kwargs['pk']
        game_results = GameResults.objects.all().filter(game = game_id)
        context['game_results'] = game_results
        context['players'] = players
        return context


class GameUpdateView(FormView):

    form_class = GameForm
    template_name = 'marstracker/game_update.html'
    success_url = reverse_lazy('marstracker:game-list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        player_id = self.kwargs['player']
        game_id = self.kwargs['game']
        game_results = GameResults.objects.get(game = game_id, player = player_id)
        context['game_result'] = game_results
        return context
    
    def get_initial(self):
        game_id = self.kwargs['game']
        player_id = self.kwargs['player']
        game = Game.objects.get(pk = game_id)
        player = Player.objects.get(pk = player_id)
        game_results = GameResults.objects.get(player = player_id,game = game_id)
        # Return the initial data for the form
        return {'final_score': game_results.final_score,
                'milestones_score': game_results.milestones_score,
                'awards_score': game_results.awards_score,
                'tr_score': game_results.tr_score,
                'card_score': game_results.card_score,
                'board_score': game_results.board_score
                }

    def form_valid(self, form, *args, **kwargs):
        game_id = self.kwargs['game']
        player_id = self.kwargs['player']
        game = Game.objects.get(pk = game_id)
        player = Player.objects.get(pk = player_id)
        game_results = GameResults.objects.get(player = player,game = game)
        player = form.cleaned_data['player'][0]
        game_results.final_score = form.cleaned_data['final_score']
        game_results.milestones_score = form.cleaned_data['milestones_score']
        game_results.awards_score = form.cleaned_data['awards_score']
        game_results.tr_score = form.cleaned_data['tr_score']
        game_results.card_score = form.cleaned_data['card_score']
        game_results.board_score = form.cleaned_data['board_score']
        # game_results.player = player
        game_results.save()
        return super().form_valid(form)
    
class GameDeleteView(DeleteView):
    model = Game
    success_url = reverse_lazy('marstracker:game-list')
    template_name = 'marstracker/game_confirm_delete.html'

class GameResultCreateView(CreateView):
    model = GameResults
    fields = ['final_score','milestones_score','awards_score','tr_score','card_score','board_score','player','game']
    template_name = 'marstracker/game_result_add.html'
    success_url = reverse_lazy('marstracker:game-list')


class GameResultsDeleteView(DeleteView):
    model = GameResults
    success_url = reverse_lazy('marstracker:game-list')
    template_name = 'marstracker/game_confirm_delete.html'


class MyLoginView(LoginView):
    template_name = 'marstracker/login.html'
    next_page = reverse_lazy('marstracker:index')

class MyLogoutView(LogoutView):
    template_name = 'marstracker/logout.html'
    next_page = reverse_lazy('marstracker:index')

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("marstracker:index")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="marstracker/register.html", context={"register_form":form})

djangoproject/marstracker/templates/marstracker/addgame.html
{% extends 'marstracker/base.html' %}
{% block content %}

<form action = {% url 'marstracker:addgame' %} method = "post">
    {% csrf_token %}
    <p><label for="inp01">First name</label>
    <input type="text" name="firstname" id="inp01" size="40"></p>
    <p><label for="inp02">Last name</label>
    <input type="text" name="lastname" id="inp02" size="40"></p>
    <p><label for="inp03">Final score</label>
    <input type="number" name="finalscore" id="inp03" size="40"></p>
    <input type="submit" name="dopost" value="Submit"/>
    <input type="button" onclick="location.href='{% url 'marstracker:index' %}'" value="Back" />
</form>

{% endblock %}

djangoproject/marstracker/templates/marstracker/addplayer.html
{% extends 'marstracker/base.html' %}
{% block content %}


<form action={% url 'marstracker:addplayer' id %} method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form> 

{% endblock%}

djangoproject/marstracker/templates/marstracker/base.html
{% extends 'marstracker/base_bootstrap.html' %}
{% comment %} {% load app_tags %} <!-- see home/templatetags/app_tags.py and dj4e-samples/settings.py --> {% endcomment %}
{% block navbar %}
<!-- https://www.w3schools.com/bootstrap/bootstrap_navbar.asp -->
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'marstracker:index' %}">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">

      <!-- Assign output of url function to a variable named
          'xyz' to use in the if statement -->
      {% url 'marstracker:game-add' as abc1 %}

      {% url 'marstracker:index' as xyz %}
      <li {% if request.get_full_path == xyz %}class="active"{% endif %}>
          <a href="{% url 'marstracker:index' %}">Home</a></li>
      <li {% if request.get_full_path == abc1 %}class="active"{% endif %}>
        <a href="{% url 'marstracker:game-add' %}">Add game</a></li>
      {% url 'marstracker:game-list' as abc2 %}
      <li {% if request.get_full_path == abc2 %}class="active"{% endif %}>
          <a href="{% url 'marstracker:game-list' %}">Game List </a></li>

      <li class="dropdown">
      <a href="#" data-toggle="dropdown" class="dropdown-toggle">Player actions
          <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="{% url 'marstracker:player-list' %}">Player list</a></li>
            <li><a href="{% url 'marstracker:player-add' %}">Add player</a></li>
        </ul>
       </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li class="dropdown">
      <!-- gravatar depends on app_tags being loaded -->
      <!-- https://brobin.me/blog/2016/07/super-simple-django-gravatar/ -->
      <a href="#" data-toggle="dropdown" class="dropdown-toggle">
        <img style="width: 25px;" src="https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y"/><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="{% url 'marstracker:logout' %}?next={% url 'marstracker:index' %}">Logout</a></li>
        </ul>
       </li>
       {% else %}
       <li><a href="{% url 'marstracker:login' %}?next={% url 'marstracker:index' %}">Login</a></li>
       <li><a href="{% url 'marstracker:register' %}?next={% url 'marstracker:index' %}">Register</a></li>
       {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

djangoproject/marstracker/templates/marstracker/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="42-42">

<meta name="dj4e-code" content="99999999">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2022-11-01">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

djangoproject/marstracker/templates/marstracker/detail.html
{% extends 'marstracker/base.html' %}
{% block content %}


{% if object %}

Game number: {{ object.id }} 

{% for player in object.players.all%}
    <li><p>{{player}}  
        {% for score in player.scores.all%}
            <li><p>{{score}}</p></li>
        {% endfor%}
    Publication date:{{player.reg_date}}

    </p></li>

{%endfor%}


{% endif%}

<br>
<input type="button" onclick="location.href='{% url 'marstracker:index' %}'" value="Back" />
{% if object %}

<a href="/marstracker/{{object.id}}/addplayer">Add a player</a>
{% else %}

<a href="/marstracker/{{object.id}}/addplayer">Add a player</a>
{% endif%}

{%endblock%}

djangoproject/marstracker/templates/marstracker/game_detail.html
{% extends 'marstracker/base.html' %}
{% block content %}


{% if game %}
    <ul>
    {% for game_result in game_results %}
        <li>
        Player: {{game_result.player}} Final score: {{game_result.final_score}}
        TR score: {{game_result.tr_score}} Board score: {{game_result.board_score}}
        Milestones score: {{game_result.milestones_score}} Awards score: {{game_results.awards_score}}
        Card score: {{game_result.card_score}}
        </li>
    {% endfor %}
    </ul>

{% endif %}

<a href="{% url 'marstracker:game-result-add' %}"> Add game </a>
<a href="{% url 'marstracker:index' %}"> Back</a>

{% endblock %}

djangoproject/marstracker/templates/marstracker/game_list.html
{% extends 'marstracker/base.html' %}
{% block content %}


{% if game_list %}

    {% for game in game_list%}
        <p>
        
        <a href = "{%url 'marstracker:game-detail' game.id %}">{{game}}</a>
        <a href = "{%url 'marstracker:game-result-add' %}">Add game result </a>  
        <a href = "{%url 'marstracker:game-delete' game.id%}"> Delete </a>
        {% for game_result in game_results%}
            {% if game.id == game_result.game_id %}
                <li>
                    Player: {{game_result.player}} Final score: {{game_result.final_score}} 
                    <a href = "{%url 'marstracker:game-result-update' game.id game_result.player.id %}">Edit</a>
                    <a href = "{%url 'marstracker:game-result-delete' game_result.id %}">Delete</a>

                </li>
            {% endif %}
        {% endfor %}
        </p>
    {% endfor %}

{% else %}
    <p>No games have been played</p>
{% endif %}

<br>
<a href="{% url 'marstracker:game-add'  %}"> Add game </a>


{%endblock%}

djangoproject/marstracker/templates/marstracker/game_update.html
{% extends 'marstracker/base.html' %}
{% block content %}


Player: {{game_result.player}}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form> 
<a href="{% url 'marstracker:game-list' %}"> Back</a>

{% endblock %}

djangoproject/marstracker/templates/marstracker/login.html
{% extends 'marstracker/base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

djangoproject/marstracker/templates/marstracker/logout.html
{% extends 'marstracker/base.html' %}

{% block content %}
  <h2>You have been logged out</h2>
{% endblock %}

djangoproject/marstracker/templates/marstracker/player_add.html
{% extends 'marstracker/base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form> 


{% endblock %}

djangoproject/marstracker/templates/marstracker/player_confirm_delete.html
{% extends 'marstracker/base.html' %}
{% block content %}


<h2>Confirm Deletion</h2>

<p>Are you sure you want to delete this item?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'marstracker:index' %}">Cancel</a>
</form>

{% endblock %}

djangoproject/marstracker/templates/marstracker/player_list.html
{% extends 'marstracker/base.html' %}
{% block content %}


{% if player_list %}
    <ul>
    {% for player in player_list %}
        <li>First name: {{player.first_name}} Last name: {{player.last_name}} 
            <a href = "{%url 'marstracker:player-update' player.id %}">Edit</a>
            <a href = "{%url 'marstracker:player-delete' player.id %}">Delete</a>
        </li>
        
    {% endfor %}    
    </ul>
{% else %}
    <p>No players are registered</p>
{% endif %}

<a href="{% url 'marstracker:player-add' %}"> Add player</a>
<a href="{% url 'marstracker:index' %}"> Back</a>

{% endblock %}

djangoproject/marstracker/templates/marstracker/register.html
{% extends "marstracker/base.html" %}

{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}